#!/bin/bash

CONTAINER="MaleficJS"

build() {
  echo "Building... $CONTAINER"
  docker build -t wmiller848/maleficjs .
}

install() {
  build
  rm -rf ./bin
  docker run --rm -v $(PWD)/bin:/host_bin wmiller848/maleficjs cp -r /opt/maleficjs/bin/. /host_bin/
  cp ./bin/dev/malefic.js $INSTALL_DIR
}

clean() {
  echo "Cleaning $CONTAINER"
  STDOUT=`docker rm maleficjs`
}

start() {
  echo "Starting... $CONTAINER"
  docker run -it -h maleficjs -P --name=maleficjs wmiller848/maleficjs bash -l
}

stop() {
  echo "Stoping... $CONTAINER"
  STDOUT=`docker stop maleficjs`
}

case $1 in
	"build")
    build
	;;
  "install")
    install
	;;
  "clean")
    clean
  ;;
  "start")
    stop
    clean
    start
  ;;
  "stop")
    stop
  ;;
  "help"|*)
    echo "./magic [CMD]"
    echo "-------------"
    echo "build - Build the docker image"
    echo "build - Build the docker image and install to ./bin"
    echo "clean - Remove the docker image"
    echo "start - Start the docker container"
    echo "stop - Stop the docker container"
  ;;
esac
